// react/todo/src/components/TodoItem.js
import React, { Component } from 'react'
import PropTypes from 'prop-types';

export class TodoItem extends Component {

  getStyle = () => {
    return {
      backgroundColor: '#f4f4f4',
      padding: '10px',
      borderBottom: '1px solid #ccc',
      textDecoration: this.props.todo.completed ? 'line-through' : 'none'
    }
  }

  render() {
    let { id, title } = this.props.todo;
    // console.log(this.props);

    return (
      <div style = { this.getStyle() }>
        <p>
          <input type="checkbox" onChange={this.props.markComplete.bind(this, id)} />
          {' '}
          { title }
          <button onClick={this.props.delTodo.bind(this, id)} style={btnStyle}>x</button>
        </p>
      </div>
    )
  }
}

TodoItem.propTypes = {
    todo: PropTypes.object.isRequired
}

let btnStyle = {
  backgroundColor: '#ff0000',
  color: '#fff',
  cursor: 'pointer',
  border: 'none',
  borderRadius: '50%',
  padding: '5px 9px',
  float: 'right',
}

export default TodoItem;

// vue/express-learning/src/components/TodoItem.vue
<template>
    <li>
        <span
            v-bind:class="{done: todo.completed}"
        >
            <input
                type="checkbox"
                v-on:change="todo.completed = !todo.completed"
            >
            <strong>{{ index + 1 }}</strong>
            {{ todo.title | uppercase }}
        </span>
        <button
            class="removeItem"
            v-on:click="$emit('remove-todo', todo.id)"
        >
            &times;
        </button>
    </li>
</template>

<script>
export default {
    props: {
        todo: {
            type: Object,
            required: true
        },
        index: Number
    },
    filters: {
        uppercase(value) {
            return value.toUpperCase();
        }
    }
}
</script>

<style scoped>
    li {
        border: 1px solid #ddd;
        display: flex;
        justify-content: space-between;
        padding: 0.5rem 2rem;
        margin-bottom: 1rem;
    }
    .removeItem {
        border-radius: 50%;
        border: none;
        background: #459;
        color: #fff;
    }
    input {
        margin-right: 1rem;
    }
    .done {
        text-decoration: line-through;
    }
</style>
