// vue/express-learning/src/components/AddTodo.vue
<template>
    <form
        @submit.prevent="onSubmit"
    >
        <input type="text" v-model="title">
        <button type="submit">Add Todo Item</button>
    </form>
</template>

<script>
export default {
    data() {
        return {
            title: ''
        }
    },
    methods: {
        onSubmit() {
            console.log('submit', this.title);
            if(this.title.trim()) {
                let newTodo = {
                    id: Date.now(),
                    title: this.title,
                    completed: false
                }

                this.$emit('add-todo', newTodo)
                this.title=''
            }
        }
    }
}
</script>

<style scoped>
    form {
        display: flex;
        justify-content: center;
    }
    input {
        width: 300px;
    }
</style>

// react/todo/src/components/AddTodo.js
import React, { Component } from 'react'

export class AddTodo extends Component {
  render() {
    return (
      <form style={{display: 'flex'}}>
        <input
            type="text"
            name="title"
            placeholder="Add Todo"
            style={{flex: '10', padding: '5px'}}
        />
        <input
            type="submit"
            value="Submit"
            className="btn"
            style={{flex: '1'}}
        />
      </form>
    )
  }
}

export default AddTodo
